apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
        - env:
            - name: MONGODB_DATABASE
              value: posts
            - name: MONGODB_DOCKER_PORT
              value: "27017"
            - name: MONGODB_LOCAL_PORT
              value: "7017"
            - name: MONGODB_PASSWORD
              value: abcd
            - name: MONGODB_USER
              value: root
            - name: NODE_DOCKER_PORT
              value: "8080"
            - name: NODE_LOCAL_PORT
              value: "6868"
          image: mongo:5.0.2
          name: mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: db
      restartPolicy: Always
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db
