apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mongodb
            - name: DB_NAME
              value: posts
            - name: DB_PASSWORD
              value: abcd
            - name: DB_PORT
              value: "27017"
            - name: DB_USER
              value: root
            - name: MONGODB_DATABASE
              value: posts
            - name: MONGODB_DOCKER_PORT
              value: "27017"
            - name: MONGODB_LOCAL_PORT
              value: "7017"
            - name: MONGODB_PASSWORD
              value: abcd
            - name: MONGODB_USER
              value: root
            - name: NODE_DOCKER_PORT
              value: "8080"
            - name: NODE_LOCAL_PORT
              value: "6868"
          image: zizou91/woc_app:latest
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP
          stdin: true
          tty: true
      restartPolicy: Always
